START TRANSACTION;

-- Insertar 195 países

INSERT INTO Countries (name, iso_code, itu_code, continent, status) VALUES
('Afganistán', 'AF', '+93', 'Asia', 'Active'),
('Albania', 'AL', '+355', 'Europa', 'Active'),
('Alemania', 'DE', '+49', 'Europa', 'Active'),
('Andorra', 'AD', '+376', 'Europa', 'Active'),
('Angola', 'AO', '+244', 'África', 'Active'),
('Antigua y Barbuda', 'AG', '+1-268', 'América', 'Active'),
('Arabia Saudita', 'SA', '+966', 'Asia', 'Active'),
('Argentina', 'AR', '+54', 'América', 'Active'),
('Armenia', 'AM', '+374', 'Asia', 'Active'),
('Australia', 'AU', '+61', 'Oceanía', 'Active'),
('Austria', 'AT', '+43', 'Europa', 'Active'),
('Azerbaiyán', 'AZ', '+994', 'Asia', 'Active'),
('Bahamas', 'BS', '+1-242', 'América', 'Active'),
('Bangladesh', 'BD', '+880', 'Asia', 'Active'),
('Barbados', 'BB', '+1-246', 'América', 'Active'),
('Baréin', 'BH', '+973', 'Asia', 'Active'),
('Bélgica', 'BE', '+32', 'Europa', 'Active'),
('Belice', 'BZ', '+501', 'América', 'Active'),
('Benín', 'BJ', '+229', 'África', 'Active'),
('Bielorrusia', 'BY', '+375', 'Europa', 'Active'),
('Birmania', 'MM', '+95', 'Asia', 'Active'),
('Bolivia', 'BO', '+591', 'América', 'Active'),
('Bosnia y Herzegovina', 'BA', '+387', 'Europa', 'Active'),
('Botsuana', 'BW', '+267', 'África', 'Active'),
('Brasil', 'BR', '+55', 'América', 'Active'),
('Brunéi', 'BN', '+673', 'Asia', 'Active'),
('Bulgaria', 'BG', '+359', 'Europa', 'Active'),
('Burkina Faso', 'BF', '+226', 'África', 'Active'),
('Burundi', 'BI', '+257', 'África', 'Active'),
('Cabo Verde', 'CV', '+238', 'África', 'Active'),
('Camboya', 'KH', '+855', 'Asia', 'Active'),
('Camerún', 'CM', '+237', 'África', 'Active'),
('Canadá', 'CA', '+1', 'América', 'Active'),
('Chad', 'TD', '+235', 'África', 'Active'),
('Chile', 'CL', '+56', 'América', 'Active'),
('China', 'CN', '+86', 'Asia', 'Active'),
('Chipre', 'CY', '+357', 'Europa', 'Active'),
('Colombia', 'CO', '+57', 'América', 'Active'),
('Comoras', 'KM', '+269', 'África', 'Active'),
('Congo', 'CG', '+242', 'África', 'Active'),
('Congo (República Democrática)', 'CD', '+243', 'África', 'Active'),
('Corea del Norte', 'KP', '+850', 'Asia', 'Active'),
('Corea del Sur', 'KR', '+82', 'Asia', 'Active'),
('Costa Rica', 'CR', '+506', 'América', 'Active'),
('Croacia', 'HR', '+385', 'Europa', 'Active'),
('Cuba', 'CU', '+53', 'América', 'Active'),
('Curazao', 'CW', '+599', 'América', 'Active'),
('Cyprus', 'CY', '+357', 'Europa', 'Active'),
('Chequia', 'CZ', '+420', 'Europa', 'Active'),
('Dinamarca', 'DK', '+45', 'Europa', 'Active'),
('Djibouti', 'DJ', '+253', 'África', 'Active'),
('Dominica', 'DM', '+1-767', 'América', 'Active'),
('República Dominicana', 'DO', '+1-809', 'América', 'Active'),
('Ecuador', 'EC', '+593', 'América', 'Active'),
('Egipto', 'EG', '+20', 'África', 'Active'),
('El Salvador', 'SV', '+503', 'América', 'Active'),
('Emiratos Árabes Unidos', 'AE', '+971', 'Asia', 'Active'),
('Eslovaquia', 'SK', '+421', 'Europa', 'Active'),
('Eslovenia', 'SI', '+386', 'Europa', 'Active'),
('España', 'ES', '+34', 'Europa', 'Active'),
('Estados Unidos', 'US', '+1', 'América', 'Active'),
('Estonia', 'EE', '+372', 'Europa', 'Active'),
('Eswatini', 'SZ', '+268', 'África', 'Active'),
('Etiopía', 'ET', '+251', 'África', 'Active'),
('Fiyi', 'FJ', '+679', 'Oceanía', 'Active'),
('Filipinas', 'PH', '+63', 'Asia', 'Active'),
('Finlandia', 'FI', '+358', 'Europa', 'Active'),
('Francia', 'FR', '+33', 'Europa', 'Active'),
('Gabón', 'GA', '+241', 'África', 'Active'),
('Gambia', 'GM', '+220', 'África', 'Active'),
('Georgia', 'GE', '+995', 'Asia', 'Active'),
('Ghana', 'GH', '+233', 'África', 'Active'),
('Granada', 'GD', '+1-473', 'América', 'Active'),
('Grecia', 'GR', '+30', 'Europa', 'Active'),
('Guatemala', 'GT', '+502', 'América', 'Active'),
('Guinea', 'GN', '+224', 'África', 'Active'),
('Guinea-Bisáu', 'GW', '+245', 'África', 'Active'),
('Guinea Ecuatorial', 'GQ', '+240', 'África', 'Active'),
('Guyana', 'GY', '+592', 'América', 'Active'),
('Haití', 'HT', '+509', 'América', 'Active'),
('Honduras', 'HN', '+504', 'América', 'Active'),
('Hungría', 'HU', '+36', 'Europa', 'Active'),
('India', 'IN', '+91', 'Asia', 'Active'),
('Indonesia', 'ID', '+62', 'Asia', 'Active'),
('Irán', 'IR', '+98', 'Asia', 'Active'),
('Iraq', 'IQ', '+964', 'Asia', 'Active'),
('Irlanda', 'IE', '+353', 'Europa', 'Active'),
('Isla Mauricio', 'MU', '+230', 'África', 'Active'),
('Islandia', 'IS', '+354', 'Europa', 'Active'),
('Israel', 'IL', '+972', 'Asia', 'Active'),
('Italia', 'IT', '+39', 'Europa', 'Active'),
('Jamaica', 'JM', '+1-876', 'América', 'Active'),
('Japón', 'JP', '+81', 'Asia', 'Active'),
('Jordania', 'JO', '+962', 'Asia', 'Active'),
('Kazajistán', 'KZ', '+7', 'Asia', 'Active'),
('Kenia', 'KE', '+254', 'África', 'Active'),
('Kirguistán', 'KG', '+996', 'Asia', 'Active'),
('Kiribati', 'KI', '+686', 'Oceanía', 'Active'),
('Kuwait', 'KW', '+965', 'Asia', 'Active'),
('Laos', 'LA', '+856', 'Asia', 'Active'),
('Lesoto', 'LS', '+266', 'África', 'Active'),
('Letonia', 'LV', '+371', 'Europa', 'Active'),
('Líbano', 'LB', '+961', 'Asia', 'Active'),
('Liberia', 'LR', '+231', 'África', 'Active'),
('Libia', 'LY', '+218', 'África', 'Active'),
('Liechtenstein', 'LI', '+423', 'Europa', 'Active'),
('Lituania', 'LT', '+370', 'Europa', 'Active'),
('Luxemburgo', 'LU', '+352', 'Europa', 'Active'),
('Madagascar', 'MG', '+261', 'África', 'Active'),
('Malasia', 'MY', '+60', 'Asia', 'Active'),
('Malaui', 'MW', '+265', 'África', 'Active'),
('Maldivas', 'MV', '+960', 'Asia', 'Active'),
('Malí', 'ML', '+223', 'África', 'Active'),
('Malta', 'MT', '+356', 'Europa', 'Active'),
('Marruecos', 'MA', '+212', 'África', 'Active'),
('Mauritania', 'MR', '+222', 'África', 'Active'),
('México', 'MX', '+52', 'América', 'Active'),
('Micronesia', 'FM', '+691', 'Oceanía', 'Active'),
('Mónaco', 'MC', '+377', 'Europa', 'Active'),
('Mongolia', 'MN', '+976', 'Asia', 'Active'),
('Montenegro', 'ME', '+382', 'Europa', 'Active'),
('Mozambique', 'MZ', '+258', 'África', 'Active'),
('Namibia', 'NA', '+264', 'África', 'Active'),
('Nauru', 'NR', '+674', 'Oceanía', 'Active'),
('Nepal', 'NP', '+977', 'Asia', 'Active'),
('Nicaragua', 'NI', '+505', 'América', 'Active'),
('Níger', 'NE', '+227', 'África', 'Active'),
('Nigeria', 'NG', '+234', 'África', 'Active'),
('Noruega', 'NO', '+47', 'Europa', 'Active'),
('Nueva Zelanda', 'NZ', '+64', 'Oceanía', 'Active'),
('Omán', 'OM', '+968', 'Asia', 'Active'),
('Pakistán', 'PK', '+92', 'Asia', 'Active'),
('Palaos', 'PW', '+680', 'Oceanía', 'Active'),
('Panamá', 'PA', '+507', 'América', 'Active'),
('Papúa Nueva Guinea', 'PG', '+675', 'Oceanía', 'Active'),
('Paraguay', 'PY', '+595', 'América', 'Active'),
('Perú', 'PE', '+51', 'América', 'Active'),
('Polonia', 'PL', '+48', 'Europa', 'Active'),
('Portugal', 'PT', '+351', 'Europa', 'Active'),
('Puerto Rico', 'PR', '+1-787', 'América', 'Active'),
('Reino Unido', 'GB', '+44', 'Europa', 'Active'),
('República Checa', 'CZ', '+420', 'Europa', 'Active'),
('República Dominicana', 'DO', '+1-809', 'América', 'Active'),
('Rumanía', 'RO', '+40', 'Europa', 'Active'),
('Rusia', 'RU', '+7', 'Europa', 'Active'),
('Ruanda', 'RW', '+250', 'África', 'Active'),
('San Cristóbal y Nieves', 'KN', '+1-869', 'América', 'Active'),
('San Marino', 'SM', '+378', 'Europa', 'Active'),
('San Vicente y las Granadinas', 'VC', '+1-784', 'América', 'Active'),
('Samoa', 'WS', '+685', 'Oceanía', 'Active'),
('Sao Tomé y Príncipe', 'ST', '+239', 'África', 'Active'),
('Senegal', 'SN', '+221', 'África', 'Active'),
('Serbia', 'RS', '+381', 'Europa', 'Active'),
('Seychelles', 'SC', '+248', 'África', 'Active'),
('Sierra Leona', 'SL', '+232', 'África', 'Active'),
('Singapur', 'SG', '+65', 'Asia', 'Active'),
('Siria', 'SY', '+963', 'Asia', 'Active'),
('Somalia', 'SO', '+252', 'África', 'Active'),
('Sri Lanka', 'LK', '+94', 'Asia', 'Active'),
('Suazilandia', 'SZ', '+268', 'África', 'Active'),
('Sudáfrica', 'ZA', '+27', 'África', 'Active'),
('Sudán', 'SD', '+249', 'África', 'Active'),
('Sudán del Sur', 'SS', '+211', 'África', 'Active'),
('Suecia', 'SE', '+46', 'Europa', 'Active'),
('Suiza', 'CH', '+41', 'Europa', 'Active'),
('Surinam', 'SR', '+597', 'América', 'Active'),
('Siria', 'SY', '+963', 'Asia', 'Active'),
('Tailandia', 'TH', '+66', 'Asia', 'Active'),
('Tanzania', 'TZ', '+255', 'África', 'Active'),
('Togo', 'TG', '+228', 'África', 'Active'),
('Tonga', 'TO', '+676', 'Oceanía', 'Active'),
('Trinidad y Tobago', 'TT', '+1-868', 'América', 'Active'),
('Túnez', 'TN', '+216', 'África', 'Active'),
('Turkmenistán', 'TM', '+993', 'Asia', 'Active'),
('Turquía', 'TR', '+90', 'Asia', 'Active'),
('Tuvalu', 'TV', '+688', 'Oceanía', 'Active'),
('Uganda', 'UG', '+256', 'África', 'Active'),
('Ucrania', 'UA', '+380', 'Europa', 'Active'),
('Uruguay', 'UY', '+598', 'América', 'Active'),
('Uzbekistán', 'UZ', '+998', 'Asia', 'Active'),
('Vanuatu', 'VU', '+678', 'Oceanía', 'Active'),
('Vaticano', 'VA', '+39', 'Europa', 'Active'),
('Venezuela', 'VE', '+58', 'América', 'Active'),
('Vietnam', 'VN', '+84', 'Asia', 'Active'),
('Yemen', 'YE', '+967', 'Asia', 'Active'),
('Yibuti', 'DJ', '+253', 'África', 'Active'),
('Zambia', 'ZM', '+260', 'África', 'Active'),
('Zimbabue', 'ZW', '+263', 'África', 'Active');

COMMIT;
